# Generated by Django 4.2.1 on 2023-06-15 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('create_at', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumes', to='category.category')),
            ],
            options={
                'verbose_name': 'resume',
                'verbose_name_plural': 'resume',
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='ResumeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/resumeImages')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='resume.resume')),
            ],
        ),
    ]
